{
  parserClass='org.phellang.language.parser.PhelParser'

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix='Phel'
  psiImplClassSuffix='Impl'
  psiPackage='org.phellang.language.psi'

  psiImplPackage="org.phellang.language.psi.impl"

  elementTypeHolderClass="org.phellang.language.psi.PhelTypes"
  elementTypeClass="org.phellang.language.psi.PhelElementType"
  tokenTypeClass="org.phellang.language.psi.PhelTokenType"

  tokens=[
    string='regexp:"([^"]|\\")*"'
    parens_open='('
    parens_close=')'
    bracket_open='['
    bracket_close=']'
    brace_open='{'
    brace_close='}'
    comma=','
    quote="'"
    syntax_quote='`'
  ]
}

simpleFile ::= list_*
list_ ::= ( PARENS_OPEN symbol_* PARENS_CLOSE |COMMENT|CLRF)
symbol_ ::= WORD*